<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 
         http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.devpulse</groupId>
    <artifactId>users-contract</artifactId>
    <version>1.0.0</version>
    <packaging>jar</packaging>

    <name>DevPulse Users Contract</name>
    <description>API контракты для пользователей</description>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.devpulse</groupId>
            <artifactId>shared-contract</artifactId>
            <version>1.0.0</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <resources>
            <resource>
                <directory>src/main/resources/openapi</directory>
                <filtering>false</filtering>
            </resource>
        </resources>
    </build>

    <scm>
        <connection>scm:git:https://github.com/devpulse-dev/devpulse-oas.git</connection>
        <developerConnection>scm:git:https://github.com/devpulse-dev/devpulse-oas.git</developerConnection>
        <url>https://github.com/devpulse-dev/devpulse-oas</url>
        <tag>HEAD</tag>
    </scm>

    <distributionManagement>
        <repository>
            <id>github</id>
            <name>GitHub Packages</name>
            <url>https://maven.pkg.github.com/devpulse-dev/devpulse-oas</url>
        </repository>
    </distributionManagement>
</project>
