<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.devpulse</groupId>
        <artifactId>devpulse-oas-parent</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>collection-contract</artifactId>

    <name>DevPulse Collection Contract</name>
    <description>API контракты для управления сбором данных</description>

    <dependencies>
        <dependency>
            <groupId>com.devpulse</groupId>
            <artifactId>shared-contract</artifactId>
        </dependency>
    </dependencies>
</project>
